### PR TITLE
error: Add JSON formatted errors for vacate APIs

### LINKED ISSUE #164: Support JSON output errors for multierror.Prefixed
## Overview

Currently, many of our packages support outputting to JSON / text and our `multierror.Error` does not, it does support a custom formatter function, which is easy to replace.

The best way forward with this would be to allow a `JSON` format setting in the multierror.Prefixed itself, so that when `Error` is called, the output is JSON.

## Possible Implementation

Writing a package function might be the best way forward as it can provide a good API for clients to use without the need to cast to a type and having to handle that logic in the client.

```go
func WithFormat(error, FormatFunc) error 
```

Accepting an error and a format function is a good way to provide an open implementation, following that, writing a `FormatFunc` which implements a JSON formatted output can be handy.

### PR DESCRIPTION
**Pull request by marclop**
## Description

Introduces a series of changes which allow the `allocator.Vacate()` to
return a multierror which can serialize the errors to JSON format.

To do so, multiple changes have been made throughout multiple packages,
providing building blocks for other APIs to leverage these, or use on-
demand.

`multierror.WithFormat()`: modifies a `multierror.Prefixed` or hashicorp
`multierror.Error` format functions which instead of formatting with a
"text" format, return a JSON formatted string.

`apierror.JSONError{}`: wrapping any `string` with this type, will make
it compatible to `json.Marshal`-ed. A `apierror.NewJSONError()` func is
provided for convenience too, allowing errors to be wrapped in the type.

`plan.StreamJSON`: has been fixed to return the final `error` result in
JSON formatted form.

`plan`: Legacy format has now been removed since it's no longer used.

`allocatorapi.VacateError`: now used for most of the returned vacate
errors since it supports both text and JSON formats.

## Related Issues

Resolves #164 

## Types of Changes

- [x] New feature (non-breaking change which adds functionality)

### CODE REVIEW

File: pkg/multierror/format.go [hunk 1]
```diff
@@ -0,0 +1,82 @@
...
+	"bytes"
+	"encoding/json"
+	"errors"
+	"strings"
+
+	"github.com/go-openapi/swag"
+	"github.com/hashicorp/go-multierror"
+)
+
+// JSONError wraps a list of errors to be encodede in JSON format.
```
Comment (karencfv) [inline pkg/multierror/format.go:30]:
```suggestion
// JSONError wraps a list of errors to be encoded in JSON format.
```

File: pkg/multierror/format.go [hunk 2]
```diff
@@ -0,0 +1,82 @@
...
+type JSONError struct {
+	Errors []interface{} `json:"errors,omitempty"`
+}
+
+// WithFormatFunc takes in an error and tries to set the ErrorFormatFunc to the
+// passed function if the error is of type *Prefixed or *multierror.Error,
+// otherwise it returns the erorr as is.
```
Comment (karencfv) [inline pkg/multierror/format.go:37]:
```suggestion
// otherwise it returns the error as is.
```

File: pkg/multierror/format.go [hunk 3]
```diff
@@ -0,0 +1,82 @@
...
+	var errs = make([]interface{}, 0, len(es))
+	for _, e := range es {
+		var t = make(map[string]interface{})
+		if err := swag.FromDynamicJSON(e, &t); len(t) == 0 || err != nil {
+			t["message"] = e.Error()
+		}
+		errs = append(errs, t)
+	}
+
+	_ = enc.Encode(JSONError{Errors: errs})
```
Comment (karencfv) [inline pkg/multierror/format.go:79]: can we return this error?

File: pkg/plan/track_response.go [hunk 4]
```diff
@@ -41,16 +41,12 @@ type TrackResponse struct {
 	runningStep bool
 }
 
-func (res TrackResponse) Error() error {
+func (res TrackResponse) Error() string {
```
Comment (karencfv) [inline pkg/plan/track_response.go:44]: Will this change have any unintended consequences for the terraform provider?

**Review by karencfv — COMMENTED** [review]
Overall code looks great! Just left a few nits and some questions. I'll also wait on @ppapapetrou76 's 👍 to make sure the error's format in JSON is what tooling needs :)

File: pkg/plan/track_response.go (hunk 4 above)
Comment (marclop) [reply pkg/plan/track_response.go:44]: Not at all, the Terraform provider relies on the `Wait()` and the result it has, by default it returns the result of this, but if. we wanted to we could turn it into JSON. So long story short it only adds features which we can leverage ourselves.

File: pkg/multierror/format.go (hunk 3 above)
Comment (marclop) [reply pkg/multierror/format.go:79]: The function signature doesn't allow an error to be returned at the moment, so unfortunately we have to ignore this error.

In any case, because we're encoding a known structure, there's not a high likelihood of an error occurring here. I know it doesn't look great, but couldn't even trigger the error myself through the normal flow.

File: pkg/api/platformapi/allocatorapi/vacate.go [hunk 5]
```diff
@@ -119,7 +121,7 @@ func moveAllocators(params *VacateParams, p *pool.Pool) ([]pool.Validator, bool,
 
 // moveNodes moves all of the nodes off the specified allocator
 func moveNodes(id string, params *VacateParams, p *pool.Pool) ([]pool.Validator, bool, error) {
-	var merr = multierror.NewPrefixed(fmt.Sprintf("allocator %s", id))
+	var merr = multierror.NewPrefixed("vacate error")
```
Comment (ppapapetrou76) [inline pkg/api/platformapi/allocatorapi/vacate.go:124]: @Z3r0Sum does this break our error parsing in soteria?

File: pkg/api/platformapi/allocatorapi/vacate.go [hunk 6]
```diff
@@ -473,14 +477,16 @@ func CheckVacateFailures(failures *models.MoveClustersDetails, filter []string)
 		var ferr error
 		if len(failure.Errors) > 0 {
 			var err = failure.Errors[0]
-			ferr = fmt.Errorf("code: %s, message: %s", *err.Code, *err.Message)
+			ferr = fmt.Errorf("%s (%s)", *err.Message, *err.Code)
```
Comment (ppapapetrou76) [inline pkg/api/platformapi/allocatorapi/vacate.go:480]: @Z3r0Sum Again does this change breaks our error parsing in soteria?

File: pkg/api/platformapi/allocatorapi/vacate.go [hunk 7]
```diff
@@ -492,13 +498,17 @@ func CheckVacateFailures(failures *models.MoveClustersDetails, filter []string)
...
```
Comment (ppapapetrou76) [inline pkg/api/platformapi/allocatorapi/vacate.go:501]: Same here about soteria error parsing

File: pkg/api/platformapi/allocatorapi/vacate_full_test.go [hunk 8]
```diff
@@ -607,9 +609,115 @@ func TestVacate(t *testing.T) {
 				"\x1b[92;mDeployment [DISCOVERED_DEPLOYMENT_ID] - [Kibana][4ee11eb40eda22cac0cce259625c6734]: finished running all the plan steps\x1b[0m (Total plan duration )",
 			),
 			err: `vacate error: 2 errors occurred:
-	* resource id [3ee11eb40eda22cac0cce259625c6734][elasticsearch] failed vacating, reason: code: a code, message: a message
-	* deployment [DISCOVERED_DEPLOYMENT_ID] - [elasticsearch][5ee11eb40eda22cac0cce259625c6734]: caught error: "Unexpected error during step: [perform-snapshot]: [no.found.constructor.models.TimeoutException: Timeout]"
+	* allocator allocatorID-1: resource id [3ee11eb40eda22cac0cce259625c6734][elasticsearch]: failed vacating: a message (a code)
```
Comment (ppapapetrou76) [inline pkg/api/platformapi/allocatorapi/vacate_full_test.go:612]: Yes it definitely breaks our existing text parsing https://github.com/elastic/soteria/blob/master/app/allocator/vacate.go#L213

**Review by ppapapetrou76 — COMMENTED** [review]
It seems that we are breaking the existing text output which means that once we upgrde ecl in soteria we need to work on the vacate parsing 
Any chance to keep some backwards compatible text output and enhance only the new json format?

**Comment by marclop** [comment]
@ppapapetrou76 Yes it does break the "old" text format slightly, providing proper context for where the vacate is coming from thus the `allocator <id>:` prefix.

However my understanding is that Soteria only wanted to parse the JSON version of this, i.e. won't care about the text format going forward since `json.Unmarshal()` can take care of the details.

```go
var errs multierror.JSONError
err := json.Unmarshal(output, & errs)
...
```

File: pkg/api/platformapi/allocatorapi/vacate.go (hunk 5 above)
Comment (Z3r0Sum) [reply pkg/api/platformapi/allocatorapi/vacate.go:124]: This shouldn't break parsing; however, we'd want to update our tests to accurately reflect this change.

File: pkg/api/platformapi/allocatorapi/vacate.go (hunk 6 above)
Comment (Z3r0Sum) [reply pkg/api/platformapi/allocatorapi/vacate.go:480]: Yes, this change could cause some issues [here](https://github.com/elastic/soteria/blob/master/app/allocator/vacate.go#L319-L327)

File: pkg/api/platformapi/allocatorapi/vacate.go (hunk 7 above)
Comment (Z3r0Sum) [reply pkg/api/platformapi/allocatorapi/vacate.go:501]: +1 see link above

File: pkg/api/platformapi/allocatorapi/vacate_full_test.go (hunk 8 above)
Comment (Z3r0Sum) [reply pkg/api/platformapi/allocatorapi/vacate_full_test.go:612]: Why do you think this breaks it?  We actually don't care about the prefix as long as `resource id` or `deployment` is included.  We then proceed to do some string splitting around `[` & `]` depending on which it is.

**Review by ppapapetrou76 — APPROVED** [review]

File: pkg/multierror/format.go (hunk 3 above)
Comment (karencfv) [reply pkg/multierror/format.go:79]: Got it :) Sorry for the stubbornness this time, but I'm generally not a fan of ignoring errors 🤔 Is changing the function's signature to return an error too much of a hassle?

Comment (marclop) [reply pkg/multierror/format.go:79]: I didn't change the function signature for a reason, and that reason is that the likelihood off this returning an error is close to none, because we're explicitly calling `.Encode` with a structure which has JSON struct tags set (`JSONError`). The `.Encode` function returns an error because it accepts an `interface{}` which is so broad that errors might be returned if another type might be passed here like an `int` or a `string`.

**Review by karencfv — APPROVED** [review]
Thanks for clearing up my questions!
